spring:
  datasource:
    url: jdbc:postgresql://db:5432/tfg_db
    username: tfg_user
    password: tfg_pass

  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        model: llama3.2:3b
      embedding:
        model: mxbai-embed-large

    vectorstore:
      pgvector:
        table-name: vector_store
        id-type: TEXT

jwt:
  secret: test-secret-key-test-secret-key-test
