server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://db:5432/tfg_db
    username: tfg_user
    password: tfg_pass
  jpa:
    hibernate:
      ddl-auto: validate
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
      embedding:
        model: mxbai-embed-large

management:
  endpoints:
    web:
      exposure:
        include: health,info
